### ISSUE TITLE
Generator.dio doesn't work

### ISSUE THREAD

**Issue by jiffstudio** [gibahjoe/openapi-generator-dart#99] opened 2023-08-25 02:50 UTC
### Description of the bug

I chose the generatorName as Generator.dio. But it produces dart version.

### Steps to reproduce

@Openapi(
    additionalProperties:
    DioProperties(pubName: 'coclass_api', pubAuthor: 'Jiff'),
    inputSpecFile: 'lib/apis/api_spec.yaml',
    generatorName: Generator.dio,
    outputDirectory: 'plugins/coclass_api',
    useNextGen: true)
class CustomOpenapiGeneratorConfig extends OpenapiGeneratorConfig {}

### Expected behavior

Expect it to use dio to request. But it only uses http library.

### Platform

Windows

### Library version

4.12.1

### Flutter version

3.13.1

### Flutter channel

stable

**Comment by gibahjoe** [comment] 2023-08-25 11:40
HI, did you try deleting the coclass_api folder and running the generator again?

when you do, look for a log that says something like ```generate -I lib/apis/api_spec.yaml``` or something like that and paste here.

Also, if you find that the generator is not running, make a simple modification to the file that has the @openapi annotation so that build runner will detect changes and run the generator.
Awaiting your feedback.

**Comment by aschulz90** [comment] 2023-12-09 10:54
I can confirm that the generator always uses the `dart` generator, regardless of what is defined.

Version: `4.13.1`

Config:
```
@Openapi(
  additionalProperties: DioAltProperties(
    pubName: 'wichteln_api',
    pubAuthor: 'Andreas Schulz',
    nullSafe: true,
    nullSafeArrayDefault: true,
    listAnyOf: true,
  ),
  inputSpecFile: 'wichteln-api.yaml',
  generatorName: Generator.dio,
  outputDirectory: 'wichteln_api',
  alwaysRun: true,
)
```

Log:
```
[ generate -o=wichteln_api -i=wichteln-api.yaml -g=dart --additional-properties=allowUnicodeIdentifiers=false,ensureUniqueParams=true,useEnumExtension=true,prependFormOrBodyParameters=false,pubAuthor=Andreas Schulz,pubName=wichteln_api,legacyDiscriminatorBehavior=true,sortModelPropertiesByRequiredFlag=true,sortParamsByRequiredFlag=true,wrapper=none,nullSafe=true,nullSafe-array-default=true,listAnyOf=true ]
```

So every parameter seems to be applied correctly, except `-g=dart`.

**Comment by quyenvsp** [comment] 2024-03-08 04:15
it happen when your pub outdated (usually source_gen) so you can fix by run `flutter pub upgrade` (maybe --major-versions)

**Comment by gibahjoe** [comment] 2024-11-13 08:32
Closing this since this has been fixed for a while now.

**Closed by gibahjoe** 2024-11-13 08:32 UTC
Labels: bug
