### ISSUE TITLE
generator fails for v2.0.0 and 3.0.0-nullsafety.1

### ISSUE THREAD

**Issue by BeliliFahem** [gibahjoe/openapi-generator-dart#28] opened 2020-12-30 15:53 UTC
[WARNING] openapi_generator:openapi_generator on lib/com/muqel/config/OpenapiGenConfig.dart:
Executing command [generate -i lib/muqel-openapi.yaml -g dart2-api -o api/muqel_api --additional-properties=pubAuthor=Belili Fahem,pubName=muqel_api]
[INFO] 2.8s elapsed, 56/57 actions completed.
[WARNING] openapi_generator:openapi_generator on lib/com/muqel/config/OpenapiGenConfig.dart:
```
Exception in thread "main" java.lang.NoSuchFieldError: isMapContainer
	at cd.connect.openapi.DartV3ApiGenerator.lambda$updateAllModels$2(DartV3ApiGenerator.java:192)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at cd.connect.openapi.DartV3ApiGenerator.lambda$updateAllModels$3(DartV3ApiGenerator.java:172)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at cd.connect.openapi.DartV3ApiGenerator.lambda$updateAllModels$4(DartV3ApiGenerator.java:162)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cd.connect.openapi.DartV3ApiGenerator.updateAllModels(DartV3ApiGenerator.java:158)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:504)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:875)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

[WARNING] openapi_generator:openapi_generator on lib/com/muqel/config/OpenapiGenConfig.dart:
OpenapiGenerator :: Codegen Failed
[INFO] Running build completed, took 3.3s

**Comment by gibahjoe** [comment] 2020-12-31 06:59
Hello @BeliliFahem,

Season greetings.

This is a known issue with the dart2_api generator and is being tracked here https://github.com/dart-ogurets/dart-openapi-maven/issues/20

A work around however is to downgrade to version ```1.14``` or use the ```DART``` generator. They are very similar in functionality

duplicate of #27

**Closed by gibahjoe** 2020-12-31 06:59 UTC
