### ISSUE TITLE
type 'int' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by malaschitz** [gibahjoe/openapi-generator-dart#48] opened 2021-05-15 20:58 UTC
There is a serious problem (bug). I have property of type _double_. Sometimes API return json, where double value is whole number. openapi-generator at first create Map<String,  dynamic> object, and this property has type _int_ (when it is whole number). In next step is calling constructor _fromJson_ where is this value from map set to double type. Flutter throws exception **type 'int' is not a subtype of type 'double'**

This problem is on iOS and Android. Not on flutter for web (!). 

My workaround: everywhere in generated code I add _+ 0.0_. For example instead of:

`deviation: json[r'deviation'],`

I have 

`deviation: json[r'deviation'] + 0.0,`

Is there some other and better solution ?

**Comment by gibahjoe** [comment] 2021-05-15 21:08
Hi,

Please try this solution #35. Closing as duplicate, feel free to reopen.

**Closed by gibahjoe** 2021-05-15 21:08 UTC

**Comment by malaschitz** [comment] 2021-05-16 15:19
I do not like this workaround. It could by a source of ugly bugs.

**Comment by gibahjoe** [comment] 2021-05-16 15:27
Maybe but not necessarily depending on how you handle it. You can add checks to test if it's double or int before using it. 

The other option will be to fix the api to make sure your api returns the right value for double and int.

**Comment by gibahjoe** [comment] 2021-05-16 15:28
What version of the library are you using? And what flutter version? If you can also provide a minimal spec so that I can reproduce the error.

**Comment by malaschitz** [comment] 2021-05-16 15:40
I have flutter 2.0.6 and openapi_generator: ^3.1.2. 
Probably best convenient is workaround where is used: `typeMappings: {'double': 'num'}`. There is no need change mappings for int values.

**Comment by gibahjoe** [comment] 2021-05-16 16:06
Yeah. This should work too

**Comment by esDotDev** [comment] 2025-06-27 23:29
Just a note that you can't simply "fix the API" here, if the payload is JSON then numbers will always drop the decimal if they don't have a trailing value, it's part of the spec.

The `py` parser has the option for `floatStrictType` can we not add something like that? 
`When floatStrictType=false, the generator is more lenient and will accept integers for float fields, automatically converting them as needed`

Currently the solution is to ask the backend team to export all numbers as strings, all because the client can't support the idea that `double foo = 1` is valid code. It's quite an invasive ask and really seems like something we should be able to configure on the parsing site.
